# Generated by Django 4.2.5 on 2023-09-22 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
