# Generated by Django 4.2.5 on 2023-09-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("group", "0002_alter_group_group_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FinancialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("debit", models.DecimalField(decimal_places=6, max_digits=16)),
                ("credit", models.DecimalField(decimal_places=6, max_digits=16)),
                ("currency", models.FloatField(default=1.0)),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="group.group"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="records", to="financialtrack.tag"
                    ),
                ),
            ],
        ),
    ]
