# Generated by Django 4.2.5 on 2023-09-25 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financialtrack", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="account",
            new_name="tag",
        ),
        migrations.AddField(
            model_name="tag",
            name="created_by",
            field=models.ForeignKey(
                default=9981,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
